# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cb3a2fbb8eebf0df05fd001fad727034"
name = "my-qr-code"
handle = "my-qr-code-3"
application_url = "https://baths-edmonton-papers-motors.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-stores-in.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://baths-edmonton-papers-motors.trycloudflare.com/auth/callback",
  "https://baths-edmonton-papers-motors.trycloudflare.com/auth/shopify/callback",
  "https://baths-edmonton-papers-motors.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
